[tool.poetry]
name = "video-vote"
version = "0.1.0"
description = "A Streamlit application for video voting"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
streamlit = "^1.0.0"
streamlit-sortables = {git = "https://github.com/ohtaman/streamlit-sortables.git"}